# Continuous Integration (CI) label for any CI changes
CI:
  - ".github/**/*"

# Crate-respective labels
crate-labels:
  bus-mapping: "bus-mapping/**/*"
  circuit-benchmarks: "circuit-benchmarks/**/*"
  eth-types: "eth-types/**/*"
  external-tracer: "external-tracer/**/*"
  gadgets: "gadgets/**/*"
  geth-utils: "geth-utils/**/*"
  integration-tests: "integration-tests/**/*"
  keccak: "keccak256/**/*"
  mock: "mock/**/*"
  prover: "prover/**/*"
  zkevm-circuits: "zkevm-circuits/src/**/*"

# Additional labels for specific changes
labels:
  # Add 'T-opcode' to any changes related to opcodes in `bus-mapping` or `zkevm-circuits`.
  T-opcode:
    - "zkevm-circuits/src/evm_circuit/execution/**/*"
    - "bus-mapping/src/evm/opcodes/**/*"

  # Add 'T-bench' to any changes related to benchmarks in `circuit-benchmarks`.
  T-bench:
    - "circuit-benchmarks/**/*"
